version: '3.9'

services:
  backend1:
    build: ./backend
    ports:
      - "5001:5000"

  backend2:
    build: ./backend
    ports:
      - "5002:5000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2